/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.conversordivisasapi;

import com.google.gson.FieldNamingPolicy;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Brandon Alv
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Conversor de divisas");
      
        ImageIcon dolar = new ImageIcon("dolar.png");
        lbldolar.setIcon(new ImageIcon(dolar.getImage().getScaledInstance(lbldolar.getWidth(), lbldolar.getHeight(), Image.SCALE_SMOOTH)));
        
    }
    
    private boolean isWarning(){
        if(cboDivisa1.getSelectedIndex() == 0 || cboDivisa2.getSelectedIndex() == 0 ){
            JOptionPane.showMessageDialog(null, "Selecciona una divisa valida");
            return true;
        }else if(txtCantidad.getText().isBlank()){
             JOptionPane.showMessageDialog(null, "Ingresa una cantidad");
             return true;
        }else
            return false;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbldolar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnConvertir = new javax.swing.JButton();
        cboDivisa2 = new javax.swing.JComboBox<>();
        cboDivisa1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(lbldolar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 180, 190));

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        jLabel1.setText("Conversor de divisas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 277, 46));

        txtCantidad.setBackground(new java.awt.Color(246, 246, 246));
        txtCantidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCantidad.setToolTipText("Ingrese cantidad");
        txtCantidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 180, 40));

        btnConvertir.setBackground(new java.awt.Color(204, 255, 204));
        btnConvertir.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        btnConvertir.setText("Convertir");
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });
        jPanel1.add(btnConvertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 130, 40));

        cboDivisa2.setBackground(new java.awt.Color(204, 204, 204));
        cboDivisa2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar divisa", "MXN", "USD", "EUR", "ARS", "BOB", "BRL", "CLP", "COP" }));
        jPanel1.add(cboDivisa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 180, 38));

        cboDivisa1.setBackground(new java.awt.Color(204, 204, 204));
        cboDivisa1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar divisa", "MXN", "USD", "EUR", "ARS", "BOB", "BRL", "CLP", "COP" }));
        jPanel1.add(cboDivisa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 180, 38));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
        
        if (!isWarning()) {
            
            String divisaBase = cboDivisa1.getSelectedItem().toString();
            String divisaCambio = cboDivisa2.getSelectedItem().toString();
            String cantidad = txtCantidad.getText();
            
            PeticionDivisa consulta = new PeticionDivisa();
            //Gson gson = new GsonBuilder().setFieldNamingPolicy(FieldNamingPolicy.UPPER_CAMEL_CASE).setPrettyPrinting().create();
            Divisa divisa = consulta.peticionCambio(divisaBase, divisaCambio, cantidad);
            
            
            JOptionPane.showMessageDialog(null, "La conversion es: "+divisa.conversion_result()+" "+divisaCambio);
           
        }


        
        
    }//GEN-LAST:event_btnConvertirActionPerformed

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
       int key = evt.getKeyChar();
       boolean numeros = key>=48 && key<=57;
       
       if(!numeros)
           evt.consume();
       
    }//GEN-LAST:event_txtCantidadKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertir;
    private javax.swing.JComboBox<String> cboDivisa1;
    private javax.swing.JComboBox<String> cboDivisa2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbldolar;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
